apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: net-attach-def-veth01
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "host-device",
      "device": "to-pod",
      "ipam": {
        "type": "static",
        "addresses": [
          {
            "address": "192.168.0.10/24"
          }
        ]
      }
    }'
