apiVersion: v1
kind: Pod
metadata:
  name: netshoot-secondary-veth
  annotations:
    k8s.v1.cni.cncf.io/networks: net-attach-def-veth01
spec:
  containers:
  - name: netshoot
    image: nicolaka/netshoot
    command:
      - sleep
      - infinity
